version: "3"
services:
  malangsoftware:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      APIS: malangsoftware
    ports:
      - 8007:8007 # events
      - 8005:8005 # rohmanweb
      - 8004:8004 # malangsoftware
    command: npm run start