version: "2"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 8008:8008
    command: npm run dev