version: '3'

networks:
  malangsoftware_network:
    external: true

services:
# DOCUMENTATION
  documentations:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: node:alpine
    volumes:
      - ../nodejs:/app
      - ../logs:/logs
    working_dir: /app
    environment:
      APIS: documentations
      PORT: 4001
      DOMAIN_REF: http://localhost:8001
    ports:
      - 8001:4001 # documentation
    command: npm run dev
    networks:
      - malangsoftware_network
# # ACCOUNTS
#   accounts_api:
#     # build:
#     #   context: .
#     #   dockerfile: Dockerfile
#     image: node:alpine
#     volumes:
#       - ../nodejs:/app
#     working_dir: /app
#     environment:
#       APIS: accounts
#       PORT: 4002
#     ports:
#       - 8002:4002 # accounts
#     networks:
#       - malangsoftware_network
#     command: npm run dev
#     external_links:
#       - docker_development_mongodb_1:mongodb
# # OFFICE
#   office_api:
#     # build:
#     #   context: .
#     #   dockerfile: Dockerfile
#     image: node:alpine
#     volumes:
#       - ../nodejs:/app
#     working_dir: /app
#     environment:
#       APIS: office_malangsoftware
#       PORT: 4003
#     ports:
#       - 8003:4003 # office
#     networks:
#       - malangsoftware_network
#     command: npm run dev
#     external_links:
#       - docker_development_mongodb_1:mongodb